// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPY56nn4ScJhNcFABLXDrgx-hxRXejZVk',
    appId: '1:217934131130:web:9f78bd46f116d53d4cf783',
    messagingSenderId: '217934131130',
    projectId: 'zoovengers-10770',
    authDomain: 'zoovengers-10770.firebaseapp.com',
    storageBucket: 'zoovengers-10770.firebasestorage.app',
    measurementId: 'G-H52CGFB2B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM-s6hWXv1lNgMm8Eib-khjwpC7UFrYjc',
    appId: '1:217934131130:android:2a02d36ca617ec004cf783',
    messagingSenderId: '217934131130',
    projectId: 'zoovengers-10770',
    storageBucket: 'zoovengers-10770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6sEItTgcB0dJPuGMxtfrDB9GJDQlogGI',
    appId: '1:217934131130:ios:edd8e57955c1ffba4cf783',
    messagingSenderId: '217934131130',
    projectId: 'zoovengers-10770',
    storageBucket: 'zoovengers-10770.firebasestorage.app',
    iosBundleId: 'fr.museum.zoovengers',
  );
}
